/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mchange.io.FileUtils;
//import org.apache.commons.io.FileUtils;
import controller.AtletaController;
import controller.ObservadorController;
import controller.UsuarioController;
import dao.DaoAtletaImp;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Atleta;
import model.Observador;
import model.Usuarios;
import static org.apache.poi.hssf.usermodel.HeaderFooter.file;
import util.CopiarDiretorio;

/**
 *
 * @author brenn
 */
public class CadAtleta extends javax.swing.JInternalFrame {

    
    AtletaController control = null;
    ObservadorController patcontrol = null;
    boolean salvo = true;
    File f;
    //****
    Usuarios user;
    /******
    /**
     * Creates new form CadClubes
     */
    List<Atleta> at = new ArrayList<Atleta>();
    List<Observador> obs = new ArrayList<Observador>();
    List<Observador> carregacombo = new ArrayList<Observador>();

    int indice;

    public CadAtleta() {
        
        initComponents();
        control = new AtletaController();
        patcontrol = new ObservadorController();
        carregacombo = patcontrol.getObservador();
        obs = patcontrol.getObservador();
        txtId.setEditable(false);

        if (carregacombo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Antes de cadastrar um clube você deve cadastrar um patrocinador");
        } else {
            while (!carregacombo.isEmpty()) {
                cbxObservador.addItem(carregacombo.get(0).getNome());
                carregacombo.remove(0);
            }
            atualizaLista();
            indice = 0;
            try {
                mostrarDadosDoBancoNaTela();
            } catch (ParseException ex) {
                Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
    public CadAtleta(Usuarios use) {
       //****
        int s = use.getStatus();
        user = use;
        //******
        initComponents();
        control = new AtletaController();
        patcontrol = new ObservadorController();
        carregacombo = patcontrol.getObservador();
        obs = patcontrol.getObservador();
        txtId.setEditable(false);

        if (carregacombo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Antes de cadastrar um clube você deve cadastrar um patrocinador");
        } else {
            while (!carregacombo.isEmpty()) {
                cbxObservador.addItem(carregacombo.get(0).getNome());
                carregacombo.remove(0);
            }
            atualizaLista();
            indice = 0;
            try {
                mostrarDadosDoBancoNaTela();
            } catch (ParseException ex) {
                Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
       /* if (!txtEmail.getText().equals(use.getEmail())){
             btnExcluir.setEnabled(false);
         btnEditar.setEnabled(false);
        }*/
       //***********
        if (s==2 || s==3)
        {
            btnNovo.setEnabled(false);
           // relatorioObservador.setEnabled(false);
            
        }
        if(s==3 || !txtEmail.getText().equals(use.getEmail()) )
        {
         btnExcluir.setEnabled(false);
         btnEditar.setEnabled(false);
        }
        if(!use.isValido()){
        btnNovo.setEnabled(true);
        }
        if(s==1 ){
        txtEmail.setEditable(true);
        }
        //*****
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        txtCidade = new javax.swing.JTextField();
        txtNResponsavel = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lblNomeResponsavel = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        llbCidade = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblObservador = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtPosicao = new javax.swing.JTextField();
        lblPosicao = new javax.swing.JLabel();
        txtLast = new javax.swing.JTextField();
        lblLast = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtData = new com.toedter.calendar.JDateChooser();
        txtCelular = new javax.swing.JFormattedTextField();
        txtNumeroResponsavel = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPe = new javax.swing.JTextField();
        btnCarregar = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        buscarImagem = new javax.swing.JButton();
        lblImagem2 = new javax.swing.JLabel();
        cbxObservador = new javax.swing.JComboBox<>();
        lblLink = new javax.swing.JLabel();
        txtLink = new javax.swing.JTextField();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField4.setText("jTextField4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtCidade.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        txtAltura.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblCelular.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblCelular.setText("Celular:");

        lbTelefone.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lbTelefone.setText("Telefone:");

        lbNome.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lbNome.setText("Nome Completo:");

        lblNomeResponsavel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblNomeResponsavel.setText("Nome do Responsável:");

        lblAltura.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblAltura.setText("Altura(CM):");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblEmail.setText("Email:");

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        lblTitulo.setText("Cadastro de Atleta");

        lblId.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblId.setText("ID:");

        llbCidade.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        llbCidade.setText("Cidade");

        lblSexo.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblSexo.setText("Sexo");

        lblObservador.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblObservador.setText("Observador que é vinculado:");

        txtId.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        txtNome.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNome.setPreferredSize(new java.awt.Dimension(5, 20));

        txtPosicao.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblPosicao.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblPosicao.setText("Posição:");

        txtLast.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblLast.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblLast.setText("Ultimo  clube que atuou:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setText("Celular do Responsável:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setText("Data de nascimento:");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtNumeroResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumeroResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroResponsavelActionPerformed(evt);
            }
        });

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblPeso.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblPeso.setText("Peso(KG):");

        txtPeso.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setText("Pé Dominante:");

        txtPe.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        btnCarregar.setText("Carregar Imagem de perfil");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        txtSexo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        buscarImagem.setText("Buscar Imagem");
        buscarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarImagemActionPerformed(evt);
            }
        });

        cbxObservador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecionar--" }));

        lblLink.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblLink.setText("Link do Vídeo");

        txtLink.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/begin.png"))); // NOI18N
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.png"))); // NOI18N
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/last.png"))); // NOI18N
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(255, 255, 255));
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portfolio.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("Anexo de autorização:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNumeroResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(101, 101, 101)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(294, 294, 294)
                            .addComponent(lblTitulo))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(221, 221, 221)
                            .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(92, 92, 92)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPosicao)
                                .addComponent(txtNResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(84, 84, 84)
                            .addComponent(btnCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPe, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblAltura)
                                    .addGap(42, 42, 42)
                                    .addComponent(lblPeso))
                                .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(132, 132, 132)
                                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblLast)
                                    .addGap(61, 61, 61)
                                    .addComponent(lblObservador))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxObservador, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblEmail)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(lblImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addComponent(buscarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(190, 190, 190)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(llbCidade)
                                    .addComponent(lblLink)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTelefone)
                                    .addComponent(lblSexo)
                                    .addComponent(txtSexo)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                                .addGap(346, 346, 346))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblId)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(111, 111, 111))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lbNome)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(169, 169, 169))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblCelular)
                                    .addGap(168, 168, 168)
                                    .addComponent(lblNomeResponsavel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 538, Short.MAX_VALUE))))))
                .addGap(127, 127, 127))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarregar)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblId)
                                    .addComponent(lbNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSexo)
                                .addGap(5, 5, 5)
                                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llbCidade)
                            .addComponent(lbTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeResponsavel))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblPosicao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAltura)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPeso)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLast)
                            .addComponent(lblObservador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxObservador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail)
                        .addGap(4, 4, 4)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLink))
                    .addComponent(lblImagem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarImagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnUltimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addGap(171, 171, 171))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnPrimeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnProximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtId.setText("");
        txtNome.setText("");
        txtCelular.setText("");
        txtTelefone.setText("");
        txtCidade.setText("");
        txtLast.setText("");
        txtAltura.setText("");
        txtSexo.setText("");
        ///*****
        txtEmail.setText(user.getEmail());
        ///*****
        txtNResponsavel.setText("");
        txtPosicao.setText("");
        txtNumeroResponsavel.setText("");
        txtPeso.setText("");
        txtPe.setText("");
        txtLink.setText("");
        txtData.setDate(null);
        lblImagem.setIcon(null);
        cbxObservador.setSelectedItem("--Selecionar--");
        salvo=false;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    Atleta a = new Atleta();
        Observador ob = new Observador();
        for (int i = 0; i < this.obs.size(); i++) {
            if (cbxObservador.getSelectedItem().equals(this.obs.get(i).getNome())) {
                ob.setId(this.obs.get(i).getId());
                ob.setNome(this.obs.get(i).getNome());
                ob.setDataNascimento(this.obs.get(i).getDataNascimento());
                ob.setCpf(this.obs.get(i).getCpf());
                ob.setSexo(this.obs.get(i).getSexo());
                ob.setCidade(this.obs.get(i).getCidade());
                ob.setObsDesde(this.obs.get(i).getObsDesde());
                ob.setImagem(this.obs.get(i).getImagem());
                ob.setClubeAssociado(this.obs.get(i).getClubeAssociado());
                ob.setCelular(this.obs.get(i).getCelular());
                ob.setEmail(this.obs.get(i).getEmail());
            }
        }

        a.setId(Integer.parseInt(txtId.getText()));
        a.setNome(txtNome.getText());
        a.setCidade(txtCidade.getText());
        a.setTelefone(txtTelefone.getText());
        a.setCelular(txtCelular.getText());
        a.setNomeResponsavel(txtNResponsavel.getText());
        a.setEmail(txtEmail.getText());
        a.setPosicao(txtPosicao.getText());
        a.setAltura(txtAltura.getText());
        a.setSexo(txtSexo.getText());
        a.setLastClube(txtLast.getText());
        a.setPeDominante(txtPe.getText());
        a.setPeso(txtPeso.getText());
        a.setLink(txtLink.getText());
        a.setCelularResponsavel(txtNumeroResponsavel.getText());
        Date pegainicio = txtData.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(pegainicio);
        a.setData(data);
        a.setObservador(ob);
        control.editar(a);

        atualizaLista();
        indice = at.size() - 1;
        try {
            mostrarDadosDoBancoNaTela();
        } catch (ParseException ex) {
            Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
    indice = 0;
        try {
            mostrarDadosDoBancoNaTela();
        } catch (ParseException ex) {
            Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        indice--;
        if (indice < 0) {
            indice++;
            JOptionPane.showMessageDialog(this, "Você já está no primeiro cadastro");
        } else {
            try {
                mostrarDadosDoBancoNaTela();
            } catch (ParseException ex) {
                Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        indice++;
        if (indice > at.size() - 1) {
            indice--;
            JOptionPane.showMessageDialog(this, "Você já está no último cadastro");
        } else {
            try {
                mostrarDadosDoBancoNaTela();
            } catch (ParseException ex) {
                Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
    indice = at.size() - 1;
        try {
            mostrarDadosDoBancoNaTela();
        } catch (ParseException ex) {
            Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    if (!salvo) {
            
        Atleta a = new Atleta();
        Observador ob = new Observador();
        for (int i = 0; i < obs.size(); i++) {
            if (cbxObservador.getSelectedItem().equals(obs.get(i).getNome())) {
                ob.setId(this.obs.get(i).getId());
                ob.setNome(this.obs.get(i).getNome());
                ob.setDataNascimento(this.obs.get(i).getDataNascimento());
                ob.setCpf(this.obs.get(i).getCpf());
                ob.setSexo(this.obs.get(i).getSexo());
                ob.setCidade(this.obs.get(i).getCidade());
                ob.setObsDesde(this.obs.get(i).getObsDesde());
                ob.setImagem(this.obs.get(i).getImagem());
                ob.setClubeAssociado(this.obs.get(i).getClubeAssociado());
                ob.setCelular(this.obs.get(i).getCelular());
                ob.setEmail(this.obs.get(i).getEmail());
            }
        }

        a.setNome(txtNome.getText());
        a.setCidade(txtCidade.getText());
        a.setTelefone(txtTelefone.getText());
        a.setCelular(txtCelular.getText());
        a.setNomeResponsavel(txtNResponsavel.getText());
        a.setEmail(txtEmail.getText());
        a.setPosicao(txtPosicao.getText());
        a.setAltura(txtAltura.getText());
        a.setSexo(txtSexo.getText());
        a.setLastClube(txtLast.getText());
        a.setPeDominante(txtPe.getText());
        a.setPeso(txtPeso.getText());
        a.setLink(txtLink.getText());
        a.setCelularResponsavel(txtNumeroResponsavel.getText());
        Date pegainicio = txtData.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(pegainicio);
        a.setData(data);
        ////primera foto a do perfil a segunda da autorização
        a.setImagem(new String[2]);
        a.setObservador(ob);
        control.inserir(a);
       
        atualizaLista();
        indice = at.size() - 1;
        /////atualiza o nome da foto
        a.setImagem(new String[]{"src/arteVisual/Atleta id "+(at.get(indice).getId())+" "+(new File(lblImagem.getIcon().toString())).getName(),
        "src/arteVisual/Atleta id "+(at.get(indice).getId())+" Aut "+ new File(lblImagem2.getIcon().toString()).getName()});
         control.editar(a);
        atualizaLista();
        ////
        try {
            ////esta linha move as imagem para a pasta do projeto 
            new CopiarDiretorio().copy(new File(lblImagem.getIcon().toString()), new File("Atleta id "+(at.get(indice).getId())));
           new CopiarDiretorio().copy(new File(lblImagem2.getIcon().toString()), new File("Atleta id "+(at.get(indice).getId()+" Aut")));
//lblImagem campo da imagem de perfil                                           
            
            mostrarDadosDoBancoNaTela();
          //**************
            btnNovo.setEnabled(false);
            user.setValido(true);
            new UsuarioController().editar(user);
           //***            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Cadastro incompleto!");
            Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (IOException ex) {   
                Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        salvo=true;
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    Atleta a = new Atleta();
        Observador ob = new Observador();
        for (int i = 0; i < obs.size(); i++) {
            if (cbxObservador.getSelectedItem().equals(obs.get(i).getNome())) {
                ob.setId(this.obs.get(i).getId());
                ob.setNome(this.obs.get(i).getNome());
                ob.setDataNascimento(this.obs.get(i).getDataNascimento());
                ob.setCpf(this.obs.get(i).getCpf());
                ob.setSexo(this.obs.get(i).getSexo());
                ob.setCidade(this.obs.get(i).getCidade());
                ob.setObsDesde(this.obs.get(i).getObsDesde());
                ob.setImagem(this.obs.get(i).getImagem());
                ob.setClubeAssociado(this.obs.get(i).getClubeAssociado());
                ob.setCelular(this.obs.get(i).getCelular());
                ob.setEmail(this.obs.get(i).getEmail());
            }
        }
        a.setId(Integer.parseInt(txtId.getText()));
        a.setNome(txtNome.getText());
        a.setCidade(txtCidade.getText());
        a.setTelefone(txtTelefone.getText());
        a.setCelular(txtCelular.getText());
        a.setNomeResponsavel(txtNResponsavel.getText());
        a.setEmail(txtEmail.getText());
        a.setPosicao(txtPosicao.getText());
        a.setAltura(txtAltura.getText());
        a.setSexo(txtSexo.getText());
        a.setLastClube(txtLast.getText());
        a.setPeDominante(txtPe.getText());
        a.setPeso(txtPeso.getText());
        a.setLink(txtLink.getText());
        a.setCelularResponsavel(txtNumeroResponsavel.getText());
        Date pegainicio = txtData.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(pegainicio);
        a.setData(data);
        a.setObservador(ob);
        atualizaLista();
        indice = at.size() - 1;
        control.excluir(a);

        try {
            mostrarDadosDoBancoNaTela();
        } catch (ParseException ex) {
            Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        f = chooser.getSelectedFile();
        lblImagem.setIcon(new ImageIcon(f.toString()));
       // JOptionPane.showMessageDialog(null,lblImagem.getIcon().toString());
        
        try {
         } catch (Exception e) {
        }

    }//GEN-LAST:event_btnCarregarActionPerformed

    private void buscarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarImagemActionPerformed
    JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        f = chooser.getSelectedFile();
        lblImagem2.setIcon(new ImageIcon(f.toString()));
       // JOptionPane.showMessageDialog(null,lblImagem.getIcon().toString());
        
        try {
         } catch (Exception e) {
        }
    }//GEN-LAST:event_buscarImagemActionPerformed

    private void txtNumeroResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroResponsavelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton buscarImagem;
    private javax.swing.JComboBox<String> cbxObservador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblImagem2;
    private javax.swing.JLabel lblLast;
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblNomeResponsavel;
    private javax.swing.JLabel lblObservador;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPosicao;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel llbCidade;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private com.toedter.calendar.JDateChooser txtData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtNResponsavel;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtNumeroResponsavel;
    private javax.swing.JTextField txtPe;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPosicao;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    public void mostrarDadosDoBancoNaTela() throws ParseException {

        if (at.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não existem clubes cadastrados");
            salvo= false;
        } else {

            for (int i = 0; i < obs.size(); i++) {
                //System.out.println(at.get(indice).getObservador().getId());
                if (at.get(indice).getObservador().getId() == obs.get(i).getId()) {
                    cbxObservador.setSelectedItem(obs.get(i).getNome());
                }

            }
            //******
            if (at.get(indice).getEmail().equals(user.getEmail())) {
                btnEditar.setEnabled(true);
            }else{btnEditar.setEnabled(false);}
            //*****
            txtId.setText("" + at.get(indice).getId());
            txtNome.setText("" + at.get(indice).getNome());
            txtCelular.setText("" + at.get(indice).getCelular());
            txtTelefone.setText("" + at.get(indice).getTelefone());
            txtCidade.setText("" + at.get(indice).getCidade());
            txtLast.setText("" + at.get(indice).getLastClube());
            txtAltura.setText("" + at.get(indice).getAltura());
            txtSexo.setText("" + at.get(indice).getSexo());
            txtEmail.setText("" + at.get(indice).getEmail());
            txtPosicao.setText("" + at.get(indice).getPosicao());
            txtNResponsavel.setText("" + at.get(indice).getNomeResponsavel());
            txtPe.setText("" + at.get(indice).getPeDominante());
            txtPeso.setText("" + at.get(indice).getPeso());
            txtLink.setText("" + at.get(indice).getLink());
            txtNumeroResponsavel.setText("" + at.get(indice).getCelularResponsavel());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date data = sdf.parse(at.get(indice).getData());
            txtData.setDate(data);
            System.out.println(at.get(indice).getImagem()[0]);
            lblImagem.setIcon(new ImageIcon(at.get(indice).getImagem()[0]));
            lblImagem2.setIcon(new ImageIcon(at.get(indice).getImagem()[1]));
            System.out.println(at.get(indice).getImagem()[1]);
            
        }
    }

    public void atualizaLista() {
        at.clear();
        at = control.getAtleta();
    }
}
