/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AtletaController;
import controller.ObservadorController;
import dao.DaoAtletaImp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Atleta;
import model.Observador;

/**
 *
 * @author brenn
 */
public class CadAtleta extends javax.swing.JInternalFrame {

    AtletaController control = null;
    ObservadorController patcontrol = null;
    /**
     * Creates new form CadClubes
     */
    List<Atleta> at = new ArrayList<Atleta>();
    List<Observador> obs = new ArrayList<Observador>();
    List<Observador> carregacombo = new ArrayList<Observador>();

    int indice;

    public CadAtleta() {
        initComponents();
        control = new AtletaController();
        patcontrol = new ObservadorController();
        carregacombo = patcontrol.getObservador();
        obs = patcontrol.getObservador();
        txtId.setEditable(false);

        if (carregacombo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Antes de cadastrar um clube você deve cadastrar um patrocinador");
        } else {
            while (!carregacombo.isEmpty()) {
                cbxObservador.addItem(carregacombo.get(0).getNome());
                carregacombo.remove(0);
            }
            atualizaLista();
            indice = 0;
            try {
                mostrarDadosDoBancoNaTela();
            } catch (ParseException ex) {
                Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        llbCidade = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblObservador = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        cbxObservador = new javax.swing.JComboBox<>();
        txtCidade = new javax.swing.JTextField();
        txtNResponsavel = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lblNomeResponsavel = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtPosicao = new javax.swing.JTextField();
        lblPosicao = new javax.swing.JLabel();
        txtLast = new javax.swing.JTextField();
        lblLast = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtData = new com.toedter.calendar.JDateChooser();
        txtCelular = new javax.swing.JFormattedTextField();
        txtNumeroResponsavel = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPe = new javax.swing.JTextField();
        lblLink = new javax.swing.JLabel();
        txtLink = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setBorder(new javax.swing.border.MatteBorder(null));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTitulo.setText("Cadastro de Atleta");

        lblId.setText("ID:");

        llbCidade.setText("Cidade");

        lblSexo.setText("Sexo");

        lblObservador.setText("Observador:");

        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });

        btnPrimeiro.setText("|<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setText(">>");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-file.png"))); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/resume.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash-can.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        cbxObservador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecionar--" }));
        cbxObservador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxObservadorActionPerformed(evt);
            }
        });

        lblCelular.setText("Celular:");

        lbTelefone.setText("Telefone:");

        lbNome.setText("Nome:");

        lblNomeResponsavel.setText("Responsável:");

        lblAltura.setText("Altura(CM):");

        lblEmail.setText("Email:");

        lblPosicao.setText("Posição:");

        txtLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastActionPerformed(evt);
            }
        });

        lblLast.setText("Ultimo Clube:");

        jLabel1.setText("Celular do Responsável:");

        jLabel2.setText("Data de nascimento:");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtNumeroResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblPeso.setText("Peso(KG):");

        jLabel3.setText("Pé Dominante");

        lblLink.setText("Link Youtube:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSalvar)))
                                    .addComponent(lblTitulo)))
                            .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(lbTelefone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTelefone))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEmail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(llbCidade)
                                            .addGap(10, 10, 10))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblCelular)
                                                .addComponent(lblNomeResponsavel)
                                                .addComponent(jLabel2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                            .addComponent(txtNumeroResponsavel)
                                            .addComponent(txtCidade))
                                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblId, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcluir)
                                    .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(lblLast)
                                        .addComponent(lblObservador)
                                        .addComponent(lblLink))
                                    .addComponent(lblAltura, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPeso, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPosicao, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                        .addComponent(txtPosicao)
                                        .addComponent(txtAltura))
                                    .addComponent(txtPe, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxObservador, 0, 171, Short.MAX_VALUE)
                                    .addComponent(txtLast, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txtLink))))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNome))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPosicao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAltura)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCelular)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSexo)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(lblNomeResponsavel)
                        .addComponent(txtPe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumeroResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLast)
                        .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(llbCidade))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTelefone))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxObservador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObservador))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLink)
                            .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnProximo)
                        .addComponent(btnUltimo))
                    .addComponent(btnAnterior, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtId.setText("");
        txtNome.setText("");
        txtCelular.setText("");
        txtTelefone.setText("");
        txtCidade.setText("");
        txtLast.setText("");
        txtAltura.setText("");
        txtSexo.setText("");
        txtEmail.setText("");
        txtNResponsavel.setText("");
        txtPosicao.setText("");
        txtNumeroResponsavel.setText("");
        txtPeso.setText("");
        txtPe.setText("");
        txtLink.setText("");
        txtData.setDate(null);
        cbxObservador.setSelectedItem("--Selecionar--");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Atleta a = new Atleta();
        Observador ob = new Observador();
        for (int i = 0; i < this.obs.size(); i++) {
            if (cbxObservador.getSelectedItem().equals(this.obs.get(i).getNome())) {
                ob.setId(this.obs.get(i).getId());
                ob.setNome(this.obs.get(i).getNome());
                ob.setDataNascimento(this.obs.get(i).getDataNascimento());
                ob.setCpf(this.obs.get(i).getCpf());
                ob.setSexo(this.obs.get(i).getSexo());
                ob.setCidade(this.obs.get(i).getCidade());
                ob.setObsDesde(this.obs.get(i).getObsDesde());
                ob.setAnexo(this.obs.get(i).getAnexo());
                ob.setAtletasAssociado(this.obs.get(i).getAtletasAssociado());
                ob.setCelular(this.obs.get(i).getCelular());
                ob.setEmail(this.obs.get(i).getEmail());
            }
        }

        a.setId(Integer.parseInt(txtId.getText()));
        a.setNome(txtNome.getText());
        a.setCidade(txtCidade.getText());
        a.setTelefone(txtTelefone.getText());
        a.setCelular(txtCelular.getText());
        a.setNomeResponsavel(txtNResponsavel.getText());
        a.setEmail(txtEmail.getText());
        a.setPosicao(txtPosicao.getText());
        a.setAltura(txtAltura.getText());
        a.setSexo(txtSexo.getText());
        a.setLastClube(txtLast.getText());
        a.setPeDominante(txtPe.getText());
        a.setPeso(txtPeso.getText());
        a.setLink(txtLink.getText());
        a.setCelularResponsavel(txtNumeroResponsavel.getText());
        Date pegainicio = txtData.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(pegainicio);
        a.setData(data);
        System.out.println(a.getData());
        a.setObservador(ob);
        control.editar(a);

        atualizaLista();
        indice = at.size() - 1;
        try {
            mostrarDadosDoBancoNaTela();
        } catch (ParseException ex) {
            Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        indice = 0;
        try {
            mostrarDadosDoBancoNaTela();
        } catch (ParseException ex) {
            Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        indice--;
        if (indice < 0) {
            indice++;
            JOptionPane.showMessageDialog(this, "Você já está no primeiro cadastro");
        } else {
            try {
                mostrarDadosDoBancoNaTela();
            } catch (ParseException ex) {
                Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        indice++;
        if (indice > at.size() - 1) {
            indice--;
            JOptionPane.showMessageDialog(this, "Você já está no último cadastro");
        } else {
            try {
                mostrarDadosDoBancoNaTela();
            } catch (ParseException ex) {
                Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        indice = at.size() - 1;
        try {
            mostrarDadosDoBancoNaTela();
        } catch (ParseException ex) {
            Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Atleta a = new Atleta();
        Observador ob = new Observador();
        for (int i = 0; i < obs.size(); i++) {
            if (cbxObservador.getSelectedItem().equals(obs.get(i).getNome())) {
                ob.setId(this.obs.get(i).getId());
                ob.setNome(this.obs.get(i).getNome());
                ob.setDataNascimento(this.obs.get(i).getDataNascimento());
                ob.setCpf(this.obs.get(i).getCpf());
                ob.setSexo(this.obs.get(i).getSexo());
                ob.setCidade(this.obs.get(i).getCidade());
                ob.setObsDesde(this.obs.get(i).getObsDesde());
                ob.setAnexo(this.obs.get(i).getAnexo());
                ob.setAtletasAssociado(this.obs.get(i).getAtletasAssociado());
                ob.setCelular(this.obs.get(i).getCelular());
                ob.setEmail(this.obs.get(i).getEmail());
            }
        }

        a.setNome(txtNome.getText());
        a.setCidade(txtCidade.getText());
        a.setTelefone(txtTelefone.getText());
        a.setCelular(txtCelular.getText());
        a.setNomeResponsavel(txtNResponsavel.getText());
        a.setEmail(txtEmail.getText());
        a.setPosicao(txtPosicao.getText());
        a.setAltura(txtAltura.getText());
        a.setSexo(txtSexo.getText());
        a.setLastClube(txtLast.getText());
        a.setPeDominante(txtPe.getText());
        a.setPeso(txtPeso.getText());
        a.setLink(txtLink.getText());
        a.setCelularResponsavel(txtNumeroResponsavel.getText());
        Date pegainicio = txtData.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(pegainicio);
        a.setData(data);
        System.out.println(a.getData());
        a.setObservador(ob);
        atualizaLista();
        indice = at.size() - 1;
        control.inserir(a);
        try {
            mostrarDadosDoBancoNaTela();
        } catch (ParseException ex) {
            Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Atleta a = new Atleta();
        Observador ob = new Observador();
        for (int i = 0; i < obs.size(); i++) {
            if (cbxObservador.getSelectedItem().equals(obs.get(i).getNome())) {
                ob.setId(this.obs.get(i).getId());
                ob.setNome(this.obs.get(i).getNome());
                ob.setDataNascimento(this.obs.get(i).getDataNascimento());
                ob.setCpf(this.obs.get(i).getCpf());
                ob.setSexo(this.obs.get(i).getSexo());
                ob.setCidade(this.obs.get(i).getCidade());
                ob.setObsDesde(this.obs.get(i).getObsDesde());
                ob.setAnexo(this.obs.get(i).getAnexo());
                ob.setAtletasAssociado(this.obs.get(i).getAtletasAssociado());
                ob.setCelular(this.obs.get(i).getCelular());
                ob.setEmail(this.obs.get(i).getEmail());
            }
        }
        a.setId(Integer.parseInt(txtId.getText()));
        a.setNome(txtNome.getText());
        a.setCidade(txtCidade.getText());
        a.setTelefone(txtTelefone.getText());
        a.setCelular(txtCelular.getText());
        a.setNomeResponsavel(txtNResponsavel.getText());
        a.setEmail(txtEmail.getText());
        a.setPosicao(txtPosicao.getText());
        a.setAltura(txtAltura.getText());
        a.setSexo(txtSexo.getText());
        a.setLastClube(txtLast.getText());
        a.setPeDominante(txtPe.getText());
        a.setPeso(txtPeso.getText());
        a.setLink(txtLink.getText());
        a.setCelularResponsavel(txtNumeroResponsavel.getText());
        Date pegainicio = txtData.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(pegainicio);
        a.setData(data);
        System.out.println(a.getData());
        a.setObservador(ob);
        atualizaLista();
        indice = at.size() - 1;
        control.excluir(a);

        try {
            mostrarDadosDoBancoNaTela();
        } catch (ParseException ex) {
            Logger.getLogger(CadAtleta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void cbxObservadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxObservadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxObservadorActionPerformed

    private void txtLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<String> cbxObservador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLast;
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblNomeResponsavel;
    private javax.swing.JLabel lblObservador;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPosicao;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel llbCidade;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private com.toedter.calendar.JDateChooser txtData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtNResponsavel;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtNumeroResponsavel;
    private javax.swing.JTextField txtPe;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPosicao;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    public void mostrarDadosDoBancoNaTela() throws ParseException {

        if (at.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não existem clubes cadastrados");
        } else {

            for (int i = 0; i < obs.size(); i++) {
                System.out.println(at.get(indice).getObservador().getId());
                if (at.get(indice).getObservador().getId() == obs.get(i).getId()) {
                    cbxObservador.setSelectedItem(obs.get(i).getNome());
                }

            }
            txtId.setText("" + at.get(indice).getId());
            txtNome.setText("" + at.get(indice).getNome());
            txtCelular.setText("" + at.get(indice).getCelular());
            txtTelefone.setText("" + at.get(indice).getTelefone());
            txtCidade.setText("" + at.get(indice).getCidade());
            txtLast.setText("" + at.get(indice).getLastClube());
            txtAltura.setText("" + at.get(indice).getPosicao());
            txtSexo.setText("" + at.get(indice).getAltura());
            txtEmail.setText("" + at.get(indice).getSexo());
            txtPosicao.setText("" + at.get(indice).getPosicao());
            txtNResponsavel.setText("" + at.get(indice).getNomeResponsavel());
            txtPe.setText("" + at.get(indice).getPeDominante());
            txtPeso.setText("" + at.get(indice).getPeso());
            txtLink.setText("" + at.get(indice).getLink());
            txtNumeroResponsavel.setText("" + at.get(indice).getCelularResponsavel());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); 
            Date data = sdf.parse(at.get(indice).getData());
            txtData.setDate(data);
        }
    }

    public void atualizaLista() {
        at.clear();
        at = control.getAtleta();
    }
}
